/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_map_system;

/**
 *
 * @author XCree
 */
public class MainMenu2 extends javax.swing.JDialog {

    /**
     * Creates new form MainMenu2
     */
    public MainMenu2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        RegisterPanel = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        EventsPanel = new javax.swing.JPanel();
        jToggleButton4 = new javax.swing.JToggleButton();
        PrintPanel = new javax.swing.JPanel();
        jToggleButton5 = new javax.swing.JToggleButton();
        MainPanel = new javax.swing.JPanel();
        HomeMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EventMain = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PrintMain = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setLayout(new java.awt.CardLayout());

        SidePanel.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/home2.png"))); // NOI18N
        jToggleButton2.setText(null);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        HomePanel.add(jToggleButton2, "card2");

        jPanel3.add(HomePanel);

        RegisterPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisterPanel.setLayout(new java.awt.CardLayout());

        SidePanel.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/reg2.png"))); // NOI18N
        jToggleButton3.setText(null);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        RegisterPanel.add(jToggleButton3, "card2");

        jPanel3.add(RegisterPanel);

        EventsPanel.setBackground(new java.awt.Color(255, 255, 255));
        EventsPanel.setLayout(new java.awt.CardLayout());

        SidePanel.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/events2.png"))); // NOI18N
        jToggleButton4.setText(null);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        EventsPanel.add(jToggleButton4, "card2");

        jPanel3.add(EventsPanel);

        PrintPanel.setBackground(new java.awt.Color(255, 255, 255));
        PrintPanel.setLayout(new java.awt.CardLayout());

        SidePanel.add(jToggleButton5);
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/print2.png"))); // NOI18N
        jToggleButton5.setText(null);
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        PrintPanel.add(jToggleButton5, "card2");

        jPanel3.add(PrintPanel);

        jSplitPane1.setLeftComponent(jPanel3);

        MainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("ALAY");

        javax.swing.GroupLayout HomeMainLayout = new javax.swing.GroupLayout(HomeMain);
        HomeMain.setLayout(HomeMainLayout);
        HomeMainLayout.setHorizontalGroup(
            HomeMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeMainLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        HomeMainLayout.setVerticalGroup(
            HomeMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeMainLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        MainPanel.add(HomeMain, "card2");

        jLabel2.setText("Ka");

        javax.swing.GroupLayout RegMainLayout = new javax.swing.GroupLayout(RegMain);
        RegMain.setLayout(RegMainLayout);
        RegMainLayout.setHorizontalGroup(
            RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegMainLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel2)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        RegMainLayout.setVerticalGroup(
            RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegMainLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel2)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        MainPanel.add(RegMain, "card3");

        jLabel3.setText("Na");

        javax.swing.GroupLayout EventMainLayout = new javax.swing.GroupLayout(EventMain);
        EventMain.setLayout(EventMainLayout);
        EventMainLayout.setHorizontalGroup(
            EventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventMainLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel3)
                .addContainerGap(584, Short.MAX_VALUE))
        );
        EventMainLayout.setVerticalGroup(
            EventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventMainLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel3)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        MainPanel.add(EventMain, "card4");

        jLabel4.setText("Bukas");

        javax.swing.GroupLayout PrintMainLayout = new javax.swing.GroupLayout(PrintMain);
        PrintMain.setLayout(PrintMainLayout);
        PrintMainLayout.setHorizontalGroup(
            PrintMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintMainLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel4)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        PrintMainLayout.setVerticalGroup(
            PrintMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintMainLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel4)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        MainPanel.add(PrintMain, "card5");

        jSplitPane1.setRightComponent(MainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(HomeMain);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(RegMain);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        MainPanel.removeAll();
        MainPanel.add(EventMain);
        MainPanel.repaint();
        MainPanel.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:      
        MainPanel.removeAll();
        MainPanel.add(PrintMain);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jToggleButton5ActionPerformed
  Boolean homesel = false ,regsel = false,eventssel = false,printsel = false;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenu2 dialog = new MainMenu2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EventMain;
    private javax.swing.JPanel EventsPanel;
    private javax.swing.JPanel HomeMain;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PrintMain;
    private javax.swing.JPanel PrintPanel;
    private javax.swing.JPanel RegMain;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.ButtonGroup SidePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables
}
