/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_map_system;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.awt.print.*;
/**
 *
 * @author XCree
 */
public class MainMenu2 extends javax.swing.JDialog {

    /**
     * Creates new form MainMenu2
     */
    public MainMenu2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setIcon();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        RegisterPanel = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        EventsPanel = new javax.swing.JPanel();
        jToggleButton4 = new javax.swing.JToggleButton();
        MainPanel = new javax.swing.JPanel();
        RegMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int col)
            {
                return false;
            }
        };
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modelSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        modelTextField = new javax.swing.JFormattedTextField();
        colorTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        fbnameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        plateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        occupationTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        schoolTextField = new javax.swing.JTextField();
        companyTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        RegisterButton = new javax.swing.JButton();
        LoadButton = new javax.swing.JToggleButton();
        ClearButton = new javax.swing.JButton();
        RegPrintButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        modelSpinner1 = new javax.swing.JSpinner();
        EventMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EventList = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int col)
            {
                return false;
            }
        };
        LoadEventButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        EventName = new javax.swing.JTextField();
        EventLocation = new javax.swing.JTextField();
        CreateButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        EventPrintButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AttendList = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int col)
            {
                return false;
            }
        };
        jLabel17 = new javax.swing.JLabel();
        Attendees = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        UIDBox = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        HomeMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));
        HomePanel.setLayout(new java.awt.CardLayout());

        SidePanel.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/home2.png"))); // NOI18N
        jToggleButton2.setIconTextGap(0);
        jToggleButton2.setName(""); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        HomePanel.add(jToggleButton2, "card2");

        jPanel3.add(HomePanel);

        RegisterPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisterPanel.setLayout(new java.awt.CardLayout());

        SidePanel.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/reg2.png"))); // NOI18N
        jToggleButton3.setIconTextGap(0);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        RegisterPanel.add(jToggleButton3, "card2");

        jPanel3.add(RegisterPanel);

        EventsPanel.setBackground(new java.awt.Color(255, 255, 255));
        EventsPanel.setLayout(new java.awt.CardLayout());

        SidePanel.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/events2.png"))); // NOI18N
        jToggleButton4.setIconTextGap(0);
        jToggleButton4.setMaximumSize(new java.awt.Dimension(200, 100));
        jToggleButton4.setMinimumSize(new java.awt.Dimension(200, 100));
        jToggleButton4.setPreferredSize(new java.awt.Dimension(200, 100));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        EventsPanel.add(jToggleButton4, "card2");

        jPanel3.add(EventsPanel);

        jSplitPane1.setLeftComponent(jPanel3);

        MainPanel.setMaximumSize(new java.awt.Dimension(1097, 768));
        MainPanel.setPreferredSize(new java.awt.Dimension(856, 768));
        MainPanel.setLayout(new java.awt.CardLayout());

        RegMain.setBackground(new java.awt.Color(0, 0, 0));
        RegMain.setFocusable(false);
        RegMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        memberTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        memberTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        memberTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        memberTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(memberTable);
        memberTable.getTableHeader().setReorderingAllowed(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Facebook Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email Address:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Plate Number:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Model:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Model Year:");

        modelSpinner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modelSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"GX", "GLX", "GLS Sport", "Super Sport"}));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Color:");

        modelTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0000"))));
        modelTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        colorTextField.setFont(modelSpinner.getFont());

        nameTextField.setFont(modelSpinner.getFont());

        fbnameTextField.setFont(modelSpinner.getFont());

        addressTextField.setFont(modelSpinner.getFont());

        emailTextField.setFont(modelSpinner.getFont());

        plateTextField.setFont(modelSpinner.getFont());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Occupation:");

        occupationTextField.setFont(modelSpinner.getFont());
        occupationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("School (if Student):");

        schoolTextField.setFont(modelSpinner.getFont());

        companyTextField.setFont(modelSpinner.getFont());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Company:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact Number:");

        contactTextField.setFont(modelSpinner.getFont());

        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterButton);

        LoadButton.setText("Load");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoadButton);

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ClearButton);

        RegPrintButton.setText("Print");
        RegPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegPrintButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegPrintButton);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Group:");

        modelSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modelSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"North", "South", "East", "West", "Regional"}));

        javax.swing.GroupLayout RegMainLayout = new javax.swing.GroupLayout(RegMain);
        RegMain.setLayout(RegMainLayout);
        RegMainLayout.setHorizontalGroup(
            RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(RegMainLayout.createSequentialGroup()
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegMainLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nameTextField))
                            .addGroup(RegMainLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fbnameTextField))
                            .addGroup(RegMainLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(addressTextField))
                            .addGroup(RegMainLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(plateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modelSpinner1))
                            .addGroup(RegMainLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(companyTextField))
                            .addGroup(RegMainLayout.createSequentialGroup()
                                .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegMainLayout.createSequentialGroup()
                                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegMainLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(emailTextField))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegMainLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(modelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegMainLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(occupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(schoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegMainLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 249, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RegMainLayout.setVerticalGroup(
            RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(RegMainLayout.createSequentialGroup()
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fbnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(plateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(modelSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(modelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(occupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(schoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(companyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(RegMain, "card3");

        EventMain.setBackground(new java.awt.Color(0, 0, 0));
        EventMain.setMaximumSize(new java.awt.Dimension(856, 766));
        EventMain.setPreferredSize(new java.awt.Dimension(856, 768));

        EventList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EventList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(EventList);
        memberTable.getTableHeader().setReorderingAllowed(false);

        LoadEventButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadEventButton.setText("Load Event");
        LoadEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadEventButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(427, 494));
        jPanel2.setMinimumSize(new java.awt.Dimension(427, 494));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Event Name:");

        EventName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventNameActionPerformed(evt);
            }
        });

        EventLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CreateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateButton.setText("Create Event");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Event Location:");

        EventPrintButton.setFont(CreateButton.getFont());
        EventPrintButton.setText("Print");
        EventPrintButton.setVisible(false);
        EventPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventPrintButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EventPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(EventLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(EventName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jLabel18)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(EventLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel18)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(391, 494));
        jPanel4.setMinimumSize(new java.awt.Dimension(391, 494));

        AttendList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AttendList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(AttendList);
        memberTable.getTableHeader().setReorderingAllowed(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total Attendees:");

        Attendees.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Attendees.setForeground(new java.awt.Color(255, 255, 255));
        Attendees.setText("0");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("UID:");

        UIDBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Register");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Attendees)
                .addGap(181, 181, 181))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel17)
                        .addGap(157, 157, 157))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(UIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(UIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(Attendees)
                .addContainerGap())
        );

        Delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Delete.setText("Delete Event");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EventMainLayout = new javax.swing.GroupLayout(EventMain);
        EventMain.setLayout(EventMainLayout);
        EventMainLayout.setHorizontalGroup(
            EventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EventMainLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LoadEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(EventMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(EventMainLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        EventMainLayout.setVerticalGroup(
            EventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoadEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EventMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        MainPanel.add(EventMain, "card4");

        HomeMain.setMaximumSize(new java.awt.Dimension(856, 768));
        HomeMain.setPreferredSize(new java.awt.Dimension(856, 768));
        HomeMain.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_map_system/HomeImage.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setIconTextGap(0);
        jLabel1.setMaximumSize(new java.awt.Dimension(1166, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1166, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1166, 768));
        HomeMain.add(jLabel1, "card2");

        MainPanel.add(HomeMain, "card2");

        jSplitPane1.setRightComponent(MainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(HomeMain);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed
 private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("bilog.png")));
    }
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(RegMain);
        MainPanel.repaint();
        MainPanel.revalidate();
        String userStatement = "Select ID,Name From Members";
			// Qualify that it is a SELECT statement.
			if (userStatement.trim().toUpperCase().startsWith("SELECT"))
			{
				// Create a CoffeeDBQuery object for the query.
                                LoadMemberEventList dbQuery = new LoadMemberEventList(userStatement);
				// Get the column names.
				String[] colNames = dbQuery.getColumnNames();
				// Get the table data.
				String[][] data = dbQuery.getTableData();
				// Display the results in a table.
                                DefaultTableModel model = new DefaultTableModel(data,colNames);
                                memberTable.setModel(model);
                        }
        jLabel11.setVisible(false);
        schoolTextField.setVisible(false);
        jLabel12.setVisible(false);
        companyTextField.setVisible(false);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        MainPanel.removeAll();
        MainPanel.add(EventMain);
        MainPanel.repaint();
        MainPanel.revalidate();        // TODO add your handling code here:
           String userStatement = "Select * From Events";
			// Qualify that it is a SELECT statement.
			if (userStatement.trim().toUpperCase().startsWith("SELECT"))
			{
				// Create a CoffeeDBQuery object for the query.
                                LoadMemberEventList dbQuery = new LoadMemberEventList(userStatement);
				// Get the column names.
				String[] colNames = dbQuery.getColumnNames();
				// Get the table data.
				String[][] data = dbQuery.getTableData();
				// Display the results in a table.
                                DefaultTableModel model = new DefaultTableModel(data,colNames);
                                EventList.setModel(model);
                        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jToggleButton2.setSelected(true);
        MainPanel.removeAll();
        MainPanel.add(HomeMain);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void occupationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationTextFieldActionPerformed
        // TODO add your handling code here:
        if(occupationTextField.getText().equals("Student")||occupationTextField.getText().equals("student"))
        {
            jLabel11.setVisible(true);
            schoolTextField.setVisible(true);
        }
        else
        {
            jLabel11.setVisible(false);
            schoolTextField.setVisible(false);
            jLabel12.setVisible(true);
            companyTextField.setVisible(true);
        }
    }//GEN-LAST:event_occupationTextFieldActionPerformed

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed

        // TODO add your handling code here:
         String UID;
        if(LoadButton.isSelected())
        {
           if(memberTable.getSelectedRow()!=-1)
           {
              
               RegisterButton.setText("Update");
               UID = memberTable.getValueAt(memberTable.getSelectedRow(), 0).toString();
               System.out.print(UID);
               try
               {
                   Call(UID);
               }
               catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           }
           else
           {
               LoadButton.setSelected(false);
               JOptionPane.showMessageDialog(null,"No selected member");
           }
        }
        else
        {
               RegisterButton.setText("Register");
               UID = "";
               memberTable.clearSelection(); 
       }
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        if(LoadButton.isSelected())
        {
            SQLCommandsJava.update("Insert Query Here");
        }
        else
        {
            SQLCommandsJava.insert("Insert Query Here");
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
            if(EventName.getText().equals("")&&EventLocation.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Event Name and Event Location Must Mot Be Empty");
            }
            else
            {
                SQLCommandsJava.insert("Insert Into Events Values ('"+EventName.getText()+"','"+EventLocation.getText()+"');");
                SQLCommandsJava.CreateEvent(EventName.getText());
                           String userStatement = "Select * From Events";
			// Qualify that it is a SELECT statement.
			if (userStatement.trim().toUpperCase().startsWith("SELECT"))
			{
				// Create a CoffeeDBQuery object for the query.
                                LoadMemberEventList dbQuery = new LoadMemberEventList(userStatement);
				// Get the column names.
				String[] colNames = dbQuery.getColumnNames();
				// Get the table data.
				String[][] data = dbQuery.getTableData();
				// Display the results in a table.
                                DefaultTableModel model = new DefaultTableModel(data,colNames);
                                EventList.setModel(model);
                        }
            }
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void LoadEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadEventButtonActionPerformed
        // TODO add your handling code here:
        String Event,Location;
         if(EventList.getSelectedRow()!=-1)
           {
               Event  = EventList.getValueAt(EventList.getSelectedRow(), 0).toString();
                Location  = EventList.getValueAt(EventList.getSelectedRow(), 1).toString();
               EventName.setText(Event);
               EventLocation.setText(Location);
                EventName.setEnabled(false);
               EventLocation.setEnabled(false);
                   String userStatement = "Select * From "+EventName.getText();
			// Qualify that it is a SELECT statement.
			if (userStatement.trim().toUpperCase().startsWith("SELECT"))
			{
				// Create a CoffeeDBQuery object for the query.
                                LoadEventAttendance dbQuery = new LoadEventAttendance(userStatement);
				// Get the column names.
				String[] colNames = dbQuery.getColumnNames();
				// Get the table data.
				String[][] data = dbQuery.getTableData();
				// Display the results in a table.
                                DefaultTableModel model = new DefaultTableModel(data,colNames);
                                AttendList.setModel(model);
                        }
                          EventPrintButton.setVisible(true);
                          CreateButton.setEnabled(false);
           }
           else
           {
               JOptionPane.showMessageDialog(null,"No selected Event");
           }
    }//GEN-LAST:event_LoadEventButtonActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         if(EventList.getSelectedRow()!=-1)
           {
               SQLCommandsJava.delete("Delete From events where Event = '"
                       +EventList.getValueAt(EventList.getSelectedRow(), 0).toString()+"'");
               SQLCommandsJava.dropevent("Drop Table `"+EventList.getValueAt(EventList.getSelectedRow(), 0).toString()+"`");
           }
           else
           {
               JOptionPane.showMessageDialog(null,"No selected Event");
           }
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CreateButton.setEnabled(true);
           EventName.setText("");
               EventLocation.setText("");
                EventName.setEnabled(true);
               EventLocation.setEnabled(true);
               EventList.clearSelection();
               UIDBox.setText("");
               AttendList.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
    },
    new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
    }
));
               EventPrintButton.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try
    {
   AttendRegister.Call(UIDBox.getText(),EventName.getText());
    }
    catch (SQLException ex)
    {
    ex.printStackTrace();
    }
        Attendees.setText(""+AttendRegister.Count);
            String userStatement = "Select * From "+EventName.getText();
			// Qualify that it is a SELECT statement.
			if (userStatement.trim().toUpperCase().startsWith("SELECT"))
			{
				// Create a CoffeeDBQuery object for the query.
                                LoadEventAttendance dbQuery = new LoadEventAttendance(userStatement);
				// Get the column names.
				String[] colNames = dbQuery.getColumnNames();
				// Get the table data.
				String[][] data = dbQuery.getTableData();
				// Display the results in a table.
                                DefaultTableModel model = new DefaultTableModel(data,colNames);
                                AttendList.setModel(model);
                        }
                               
    }//GEN-LAST:event_jButton5ActionPerformed

    private void EventPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventPrintButtonActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat(EventName.getText()+" Attendance");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try
        {
            AttendList.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_EventPrintButtonActionPerformed

    private void RegPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegPrintButtonActionPerformed
        MessageFormat header = new MessageFormat("Team MAP Member List");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try
        {
            memberTable.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot Print %s%n", e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RegPrintButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void EventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventNameActionPerformed
  Boolean homesel = false ,regsel = false,eventssel = false,printsel = false;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenu2 dialog = new MainMenu2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
 public boolean Call(String UID) throws SQLException
	{
             final String DB_URL = "jdbc:mysql://localhost:3306/teammap_db";
           Connection conn = DriverManager.getConnection(DB_URL, "root", "");
                 Statement stmt = conn.createStatement();
		String Password; // Flag
		// Create a SELECT statement to get the specified
		// row from the Coffee table.
		String sqlStatement = "SELECT * FROM members WHERE ID = '" + UID + "'";
		// Send the SELECT statement to the DBMS.
		ResultSet result = stmt.executeQuery(sqlStatement);
		boolean UIDFound; // Flag
		if (result.next())
		{
			// Display the product.
			nameTextField.setText(result.getString("Name"));
                        fbnameTextField.setText(result.getString("FB_Name"));
                        addressTextField.setText(result.getString("Address"));
                        emailTextField.setText(result.getString("Email"));
                        plateTextField.setText(result.getString("Plate"));
                        //modelSpinner1.setValue(result.getString("Groups"));
                       // modelSpinner.setValue(result.getString("Model"));
                        modelTextField.setText(result.getString("ModelYear"));
                        colorTextField.setText(result.getString("Color"));
                        //add Remaining TextFields here
                       
			
			UIDFound = true;
		}
		else
		{
			// Indicate the product was not found.
			UIDFound = false;
		}
		return UIDFound;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttendList;
    private javax.swing.JLabel Attendees;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton Delete;
    private javax.swing.JTable EventList;
    private javax.swing.JTextField EventLocation;
    private javax.swing.JPanel EventMain;
    private javax.swing.JTextField EventName;
    private javax.swing.JButton EventPrintButton;
    private javax.swing.JPanel EventsPanel;
    private javax.swing.JPanel HomeMain;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JToggleButton LoadButton;
    private javax.swing.JButton LoadEventButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RegMain;
    private javax.swing.JButton RegPrintButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.ButtonGroup SidePanel;
    private javax.swing.JTextField UIDBox;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JTextField companyTextField;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fbnameTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTable memberTable;
    private javax.swing.JSpinner modelSpinner;
    private javax.swing.JSpinner modelSpinner1;
    private javax.swing.JFormattedTextField modelTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JTextField plateTextField;
    private javax.swing.JTextField schoolTextField;
    // End of variables declaration//GEN-END:variables
}
